# https://www.elastic.co/guide/en/elasticsearch/reference/6.3/modules-node.html#master-node
version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=es-cluster"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=master"
      - "node.master=false"
      - "node.data=false"
      - "node.ingest=false"
      - "node.name=es-coordinating.{{.Task.Slot}}.{{.Node.Hostname}}"
    networks:
       - esnet
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: 'global'

  master:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=es-cluster"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=master"
      - "node.master=true"
      - "node.data=false"
      - "node.ingest=false"
      - "node.name=es-master.{{.Task.Slot}}.{{.Node.Hostname}}"
    networks:
       - esnet
    deploy:
      endpoint_mode: dnsrr
      mode: 'replicated'
      replicas: 3

  data:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=es-cluster"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=master"
      - "node.master=false"
      - "node.data=true"
      - "node.ingest=true"
      - "node.name=es-data.{{.Task.Slot}}.{{.Node.Hostname}}"
    networks:
       - esnet
    deploy:
      endpoint_mode: dnsrr
      mode: 'replicated'
      replicas: 1

networks:
  esnet:
    driver: overlay
